FROM 579019700964.dkr.ecr.us-east-1.amazonaws.com/preprod-mxnet-serving:1.4.1-cpu-py3

RUN pip install gluonnlp

RUN mkdir -p /opt/ml/code/

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/ml/code:${PATH}"

COPY fasttext_word_ngram.py train /opt/ml/code/

WORKDIR /opt/ml/code/
